Finaly writes the conf & cred files properly

diff --git a/to/nas b/to/nas
--- a/to/nas
+++ b/to/nas
@@ -121,6 +121,7 @@
 	# Creates a new entry
 	#
 		tui-echo "You may pass just a single digit to complete the IP, or a regular valid IP adress."
+		tui-echo "The entry will loop until it reaches the target IP."
 		# Lets check if its single digit or a valid ip
 		
 		while 	! p "$IP"
@@ -157,7 +158,7 @@
 		fi
 		
 		if [ "add_cred" = "$TODO" ] 
-		then	add_cred "$1" && \
+		then	add_cred "$IP" "$LABEL" && \
 				useCRED=$(tui-select $(list_CREDS)) || \
 				exit 1
 		fi
@@ -168,28 +169,47 @@
 	#
 		[ -z "$1" ] && return 1
 		tui-echo "Select which share this credential file is for:"
-		this=$(tui-select -a $(list_LABEL))
+		this="${2:-$(tui-select -a $(list_LABEL))}"
 		CRED="$DIR_NAS/$1/${this/.conf}.cred"
 		
-		DOM=$(tui-read "What domain is it in ($DOM_DEF):")
-		DOM=${DOM:-$DOM_DEF}
-		
-		USR=$(tui-read "What is the remote user ($USER):")
-		USR=${USR:-$USER}
-		
-		PW=$(tui-read -p "What is the password:")
-		
-		
-		cat > "$CRED" <<-EOF
-		username=$USR
-		password=$PW
-		domain=$DOM
-		EOF
-		
-		tui-echo
-		tui-cat "$CRED"
-		tui-yesno "Are these values correct?" && \
-			chmod 400 "$CRED" || rm -f "$CRED"
+		if [ ! -f "$CRED" ]
+		then
+			DOM=$(tui-read "What domain is it in ($DOM_DEF):")
+			DOM="${DOM:-$DOM_DEF}"
+
+			USR=$(tui-read "What is the remote user ($USER):")
+			USR="${USR:-$USER}"
+
+			# Is this even required, as it currently fails saving the right cred file reference
+		#	USR_LIST=$($AWK -F':' '{print $1}' /etc/passwd)
+		#	if ! echo "$USR_LIST" | $GREP -q "$USR"
+		#	then	tui-yesno "The passed user \"$USR\" does not exist, do you want to create it?" && \
+		#			tui-asroot "useradd $USR ; passwd -d $USR"
+		#	fi
+		#	uid=$($AWK -F':' -v usr=$USR '$1 == usr {print $3}' /etc/passwd)
+
+			#echo "${uid:-99999}" ; exit 5
+			PW=$(tui-read -p "What is the (remote) password:")
+
+
+			cat > "$CRED" <<-EOF
+			username=$USR
+			password=$PW
+			domain=$DOM
+			EOF
+
+			tui-echo
+			tui-cat "$CRED"
+			chmod 400 "$CRED"
+
+			while ! tui-yesno "Are these values correct?"
+			do 	tui-edit "$CRED"
+			done
+		fi
+		tui-yesno "try long??" && \
+			tui-conf-set -v "$LABEL" CRED "$DIR_NAS/$CRED" || \
+			tui-conf-set -v "$CONF" CRED "$CRED"
+		return 0
 	}
 	p() { ping -c 1 "$1" 1>/dev/zero 2>/dev/zero ; }
 #
@@ -210,7 +230,12 @@
 		add_new
 	fi
 	
-	if [ -z "$1" ]
+	if [ "-h" = "${1,,}" ] || [ "--help" = "${1,,}" ]
+	then	echo "Usage: 	connect nas [new|LABEL]"
+		exit 99
+	elif [ "new" = "${1,,}" ]
+	then	add_new
+	elif [ -z "$1" ]
 	then	# nothing passed, connect to only found or list existing connections
 		found=($(list_LABEL))
 		if [ -z "$found" ]
@@ -220,7 +245,7 @@
 		else	LABEL=$(tui-select -a ${found[@]})
 		fi
 	else	for arg in "${@}"
-		do	if [ -f "$DIR_NAME/$arg.conf" ]
+		do	if [ -f "$DIR_CFG/nas/$arg.conf" ]
 			then	LABEL="$arg" 
 				
 			else 	tui-printf -S $? "Configuration for \"$arg\" not found."
@@ -232,22 +257,28 @@
 	if [ "$LABEL" = "${LABEL##*/}" ]
 	then	LABEL="$DIR_NAS/$LABEL"
 	fi
-	source "$LABEL"
-	if [ -z "$(echo $CRED)" ]
+	
+	set -x
+	
+	source "${LABEL}.conf"
+	if [ -z "$(echo ${CRED/\.\/})" ]
 	then	# No cred file defined for this share
 		add_cred "$IP"
 		CRED=$(tui-select $(list_CREDS))
 		[ ! -z "$CRED" ] && \
-			tui-conf-set -v "$LABEL" CRED "$CRED"
+			tui-conf-set -v "$LABEL" CRED "$DIR_NAS/$CRED"
 	fi
 #
 #	Connect
 #
-	cmd="mount -t cifs \"//$IP/$SHARE\" \"$MP\" -o _netdev,rw,credentials=\"$DIR_NAS/$CRED\",sec=ntlmv2,fsc"
+	cmd="mount -t cifs //$IP/$SHARE $MP -o _netdev,rw,credentials=$CRED,sec=ntlmv2,fsc"
 	tui-echo "To mount \"$label\""
 	tui-asroot  "$cmd"
 	doLog "Starting: $cmd"
 	tui-status $? "Connected to \"$label\""
 	RET=$?
 	doLog "Executed with: \"$RET\" as exit code"
+	
+	set +x
+	
 	exit $RET
